//
//  VideoRecordingInteractor.swift
//  VideoRecordingDemo
//
//  Created by Dima Tsurkan on 9/26/17.
//  Copyright (c) 2017 Dima Tsurkan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol VideoRecordingBusinessLogic {
    func doSomething(request: VideoRecording.Something.Request)
}

protocol VideoRecordingDataStore {
    //var name: String { get set }
}

class VideoRecordingInteractor: VideoRecordingBusinessLogic, VideoRecordingDataStore {
    var presenter: VideoRecordingPresentationLogic?
    var worker: VideoRecordingWorker?
    //var name: String = ""
  
    // MARK: Do something
  
    func doSomething(request: VideoRecording.Something.Request) {
        worker = VideoRecordingWorker()
        worker?.doSomeWork()
    
        let response = VideoRecording.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
