//
//  VideoRecordingPresenter.swift
//  VideoRecordingDemo
//
//  Created by Dima Tsurkan on 9/26/17.
//  Copyright (c) 2017 Dima Tsurkan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol VideoRecordingPresentationLogic {
    func presentSomething(response: VideoRecording.Something.Response)
}

class VideoRecordingPresenter: VideoRecordingPresentationLogic {
    weak var viewController: VideoRecordingDisplayLogic?
  
    // MARK: Do something
  
    func presentSomething(response: VideoRecording.Something.Response) {
        
    }
}
