//
//  AudioRecordingInteractor.swift
//  VideoRecordingDemo
//
//  Created by Dima Tsurkan on 9/26/17.
//  Copyright (c) 2017 Dima Tsurkan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AudioRecordingBusinessLogic {
    func doSomething(request: AudioRecording.Something.Request)
}

protocol AudioRecordingDataStore {
    //var name: String { get set }
}

class AudioRecordingInteractor: AudioRecordingBusinessLogic, AudioRecordingDataStore {
    var presenter: AudioRecordingPresentationLogic?
    var worker: AudioRecordingWorker?
    //var name: String = ""
  
    // MARK: Do something
  
    func doSomething(request: AudioRecording.Something.Request) {
        worker = AudioRecordingWorker()
        worker?.doSomeWork()
    
        let response = AudioRecording.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
