//
//  AudioRecordingPresenter.swift
//  VideoRecordingDemo
//
//  Created by Dima Tsurkan on 9/26/17.
//  Copyright (c) 2017 Dima Tsurkan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AudioRecordingPresentationLogic {
    func presentSomething(response: AudioRecording.Something.Response)
}

class AudioRecordingPresenter: AudioRecordingPresentationLogic {
    weak var viewController: AudioRecordingDisplayLogic?
  
    // MARK: Do something
  
    func presentSomething(response: AudioRecording.Something.Response) {
        
    }
}
