//
//  AudioRecordingRouter.swift
//  VideoRecordingDemo
//
//  Created by Dima Tsurkan on 9/26/17.
//  Copyright (c) 2017 Dima Tsurkan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AudioRecordingRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol AudioRecordingDataPassing {
    var dataStore: AudioRecordingDataStore? { get }
}

class AudioRecordingRouter: NSObject, AudioRecordingRoutingLogic, AudioRecordingDataPassing {
    weak var viewController: AudioRecordingViewController?
    var dataStore: AudioRecordingDataStore?
  
    // MARK: Routing
  
    //func routeToSomewhere(segue: UIStoryboardSegue?)
    //{
    //  if let segue = segue {
    //    let destinationVC = segue.destination as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //  } else {
    //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //    navigateToSomewhere(source: viewController!, destination: destinationVC)
    //  }
    //}

    // MARK: Navigation
  
    //func navigateToSomewhere(source: AudioRecordingViewController, destination: SomewhereViewController)
    //{
    //  source.show(destination, sender: nil)
    //}
  
    // MARK: Passing data
  
    //func passDataToSomewhere(source: AudioRecordingDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
